services:
  debian-admin-web-prj:
    build: .
    container_name: debian-admin-web-prj
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
    
    # Autorise Docker à créer un environnement système complet et isolé
    privileged: true
    
    # Seuls les dossiers temporaires classiques doivent être en RAM
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    
    stop_signal: SIGRTMIN+3