- name: debian-admin-web-prj
  hosts: localhost
  connection: local
  become: yes

  tasks:
    # Mettre à jour le cache APT pour partir d'une base propre
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    # Installer Nginx
    - name: Installer Nginx
      apt:
        name:
          - nginx
        state: present
    
    # Préconfiguration des réponses interactives de slapd
    - name: Configurer le domaine LDAP par défaut
      debconf:
        name: slapd
        question: slapd/domain
        value: "iutnc-crochet-fisson.local"
        vtype: string

    - name: Configurer le mot de passe administrateur LDAP
      debconf:
        name: slapd
        question: slapd/root_password
        value: "a"
        vtype: password

    - name: Confirmer le mot de passe administrateur LDAP
      debconf:
        name: slapd
        question: slapd/root_password_again
        value: "a"
        vtype: password

    - name: Ignorer la purge de la base de données
      debconf:
        name: slapd
        question: slapd/purge_database
        value: "false"
        vtype: boolean

    # Installer et configurer LDAP avec nos préconfigurations
    - name: Installer LDAP
      apt:
        name:
          - slapd
          - ldap-utils
        state: present
      
    # Démarrer le service slapd manuellement (contournement pour le build Docker)
    - name: Démarrer le service slapd manuellement
      command: /etc/init.d/slapd start
      # On ignore les erreurs au cas où l'installation APT aurait déjà réussi à lancer le processus
      ignore_errors: yes

    # Copier le fichier LDIF vers le serveur cible
    - name: Transférer le fichier LDIF des utilisateurs
      copy:
        src: nextcloud-users.ldif
        dest: /tmp/nextcloud-users.ldif
        owner: root
        mode: '0644'
